### ISSUE TITLE
bioatlas docker images missing from docker hub

### ISSUE THREAD

**Issue by ainsofs** [bioatlas/ala-docker#23]
Great work on dockerising the ALA platform. I am trying to run it in my development environment but images referred to in the docker-compose.yml file do not exist in docker hub. Is there an alternative image I can use? https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=bioatlas&starCount=0

**Comment by mskyttner** [comment]
I hope this is not an immediate blocker for you - a temporary resolution, if you have space on your dev machine, would be running the "make" command there, it should then create those binary images locally on your machine.

And thanks for pointing this out! For us to resolve this issue, I think we just need to do a "make push" to get these images onto the Docker Hub so anyone can pull the binaries from there, removing the need for building those images locally on the dev machine using the Makefile "make" command .

**Comment by mskyttner** [comment]
There are now some images available on Docker Hub along with instructions for how to deploy on a development environment such as a laptop, please see [](https://bioatlas.github.io)
