### ISSUE TITLE
./baptize does not work on Mac 

### ISSUE THREAD

**Issue by steinho** [bioatlas/ala-docker#25]
Steins-MBP:ala-docker steinarildhoem$ make theme-dl
Downloading bioatlas wordpress theme...
Steins-MBP:ala-docker steinarildhoem$ ./baptize.sh 
**grep: warning: recursive search of stdin**
^C
Steins-MBP:ala-docker steinarildhoem$ 

Works ok on linux - no-ssl branch

**Comment by steinho** [comment]
this change helps...

#!/bin/bash

f=$(grep -r -e "https://bioatlas.se" * | cut -d: -f1 | sort -d | uniq |grep -e "baptize.sh" -v | xargs)

for i in $f; do
	echo "sed -i 's,https://bioatlas.se,http://bioatlas.se,g' $i"
	sed -i 's,https://bioatlas.se,http://bioatlas.se,g' $i
done

**Comment by steinho** [comment]
The * in grep command signals any file in local path - and not system wide

**Comment by mskyttner** [comment]
The fix for this issue provided by @steinho is now in the develop branch and will be merged into master and then closed.

**Comment by pragermh** [comment]
I'm following the asciicast[](https://bioatlas.github.io/fullpull/) on macOS Sierra, got the same error, and used the @steinho fix, which seems to work. I'm new to all this, but perhaps ./baptize.sh needs to be edited...again?

**Comment by pragermh** [comment]
Or, actually, having a closer look, it didn't work. I get this error:
```
sed -i 's,https://bioatlas.se,http://bioatlas.se,g' wordpress/themes/atlas/bioatlas-wordpress-theme-master/footer.php
sed: ordpress/themes/atlas/bioatlas-wordpress-theme-master/footer.php: No such file or directory
sed -i 's,https://bioatlas.se,http://bioatlas.se,g' wordpress/themes/atlas/bioatlas-wordpress-theme-master/home.php
sed: ordpress/themes/atlas/bioatlas-wordpress-theme-master/home.php: No such file or directory
sed -i 's,https://bioatlas.se,http://bioatlas.se,g' wordpress/themes/atlas/bioatlas-wordpress-theme-master/js/ala_custom.js
sed: ordpress/themes/atlas/bioatlas-wordpress-theme-master/js/ala_custom.js: No such file or directory
sed -i 's,https://bioatlas.se,http://bioatlas.se,g' wordpress/themes/atlas/bioatlas-wordpress-theme-master/template-part-topnav.php
sed: ordpress/themes/atlas/bioatlas-wordpress-theme-master/template-part-topnav.php: No such file or directory
```
Any ideas?

**Comment by mskyttner** [comment]
Did you use the "develop" branch? In the asciicast - which needs to be updated - another branch was used.

**Comment by pragermh** [comment]
Would that be the `git fetch origin no-ssl-for-uppsala-workshop:no-ssl-for-uppsala-workshop` bit? What should I type instead? Do I need to undo the stuff I've done so far?

**Comment by mskyttner** [comment]
Have a look here: https://stackoverflow.com/questions/1783405/how-do-i-check-out-a-remote-git-branch

I think something like 

```
git fetch origin
git checkout develop
```

might work.

**Comment by pragermh** [comment]
I think this worked:
```
git fetch
git checkout -t origin/develop
```
As it gave the following response:
```
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'
```
But now I get other errors downstream, such as:
```
Pulling dashboard (bioatlas/ala-dashboard:v0.3)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

```

**Comment by pragermh** [comment]
The `./baptize.sh` gave no response at all this time, so perhaps it's still not working?

**Comment by shahmanash** [comment]
Add the following at the beginnig of the shell scripy to get the correct sed in your OS
```
#!/bin/bash
if which gsed > /dev/null; then
	sed=gsed
else
	sed=sed
fi

```
