### ISSUE TITLE
Dashboard state province

### ISSUE THREAD

**Issue by IuriGarcia** [bioatlas/ala-docker#52]
GDay, gentlemen

In Dashboard, there is a graph called "Records by state and territory". It returns me "Not Supplied" and "Other" with 100% of records as Not Supplied. I do not know what is missing to have that graph showing the states and records by state.
[https://dashboard.ala-hml.vertigo.com.br/dashboard/](url)
My dashboard configs:
```

serverName=https://dashboard.ala-dev.vertigo.com.br
contextPath=/dashboard
security.cas.casProperties=casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilter,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath

security.cas.uriFilterPattern=
security.cas.uriExclusionFilterPattern=/images.*,/css.*,/js.*,/less.*


biocache.baseURL=https://biocache-service.ala-dev.vertigo.com.br/biocache-service
biocache.webappURL=https://ala-hub.ala-dev.vertigo.com.br/ala-hub
spatial.baseURL=https://portal-espacial.ala-dev.vertigo.com.br/ws
alahub.baseURL=https://ala-hub.ala-dev.vertigo.com.br/ala-hub
collectory.baseURL=https://collectory.ala-dev.vertigo.com.br/collectory
volunteer.baseURL=
images.baseURL=https://images.ala-dev.vertigo.com.br/images
userDetails.baseURL=http://cas.ala-dev.vertigo.com.br/cas/login

bie.baseURL=https://ala-bie.ala-dev.vertigo.com.br/ala-bie/
bie.searchPath=/search
bie.webappURL=https://ala-bie.ala-dev.vertigo.com.br/ala-bie/

bie.index.baseURL=https://bie-webservice.ala-dev.vertigo.com.br/bie-index

ala.skin=ala
ala.baseURL=https://ala-dev.vertigo.com.br
headerAndFooter.baseURL=https://ala-dev.vertigo.com.br

skin.layout=ala-main
skin.fluidLayout=true
skin.homeUrl=https://ala-dev.vertigo.com.br
skin.orgNameLong=SiBBr
skin.orgNameShort=SiBBr
skin.favicon=https://ala-dev.vertigo.com.br/img/sibbr.ico
```

**Comment by shahmanash** [comment]
The data for the panel is fetched as described here:

https://github.com/AtlasOfLivingAustralia/dashboard/blob/master/grails-app/services/au/org/ala/dashboard/MetadataService.groovy#L673

The suffix for the webservice is here:

https://github.com/AtlasOfLivingAustralia/dashboard/blob/master/src/main/groovy/au/org/ala/dashboard/Constants.groovy#L10

From the configurations that you provided, the request URL would be the following : 

https://biocache-service.ala-dev.vertigo.com.br/biocache-service/occurrences/search.json?pageSize=0&q=*:*&facets=state&flimit=200

Could you check these are valid and working .

**Comment by IuriGarcia** [comment]
It was a simple issue, it is necessary to get all spatial-service layers into biocache-backend container, and vocab files. Thank you for your attention @shahmanash !
